### ISSUE TITLE
[Spring 5.3.0] StringUtils#isEmpty has bean deprecated

### ISSUE THREAD

**Issue by btkatoufm** [terasolunaorg/terasoluna-gfw#1015]
## Description

Part of #989

Starting with Spring 5.3.0, `StringUtils#isEmpty` has been deprecated.

- Issues: https://github.com/spring-projects/spring-framework/issues/25945
- Commit: spring-projects/spring-framework@621295d

## Possible Solution

Replace.
from `org.springframework.util.StringUtils#isEmpty`
to `org.springframework.util.ObjectUtils#ObjectUtils.isEmpty`

## Affect versions

- 5.7.0.RELEASE

## Issue links
> Links to related issues.

- #989

**Comment by yoshikawaa** [comment]
https://github.com/spring-projects/spring-framework/blob/5acffaa72da10ba42fe547eeea44d8615cbf99b9/spring-core/src/main/java/org/springframework/util/StringUtils.java#L94-L98

```java
	 * @deprecated as of 5.3, in favor of {@link #hasLength(String)} and
	 * {@link #hasText(String)} (or {@link ObjectUtils#isEmpty(Object)})
```

You may better to change to `!StringUtils#hasLength` or `!StringUtils#hasText` instead of `ObjectUtils#isEmpty`.
If you use `isEmpty` without careful consideration, you may not notice the difference between an empty String and an empty String array, for example.

**Comment by btkatoufm** [comment]
> If you use isEmpty without careful consideration, you may not notice the difference between an empty String and an empty String array, for example.

I agree with you.
We want to make sure it's an empty string, so we'll use `!StringUtils#hasLength` or `!StringUtils#hasText`.
