### ISSUE TITLE
Turn off the coveralls setting.

### ISSUE THREAD

**Issue by btkatoufm** [terasolunaorg/terasoluna-gfw#1026]
## Description

Turn off the coveralls setting because you are not using the coveralls report results.

## Possible Solution

- Log in at the following URL and turn off the setting.
  https://coveralls.io/repos
- Consider removing the coveralls.
  https://github.com/terasolunaorg/terasoluna-gfw/search?q=coveralls

## Affect versions

- 5.6.x.RELEASE

## Issue links

- https://github.com/terasolunaorg/terasoluna-gfw/issues/1011

**Comment by yoshikawaa** [comment]
@btkatoufm @takahashihrzg 
Currently, we are measuring with SonarQube in our test environment, so we are not measuring coverage with Coveralls.
We want to remove Coveralls from the merge requirements, as there are many cases where developers who are not repository owners cannot merge Pull Requests because the Coveralls check is not complete.

**However, Coveralls is responsible for the repository publishing coverage, and disabling it is only a temporary and workaround measure. We need to consider how to publish the quality of the repository.**

**Comment by btkatoufm** [comment]
>The Coveralls check now completes successfully and does not need to be turned off.

I set it off because the Coveralls check didn't complete successfully, but when I turned it back on, it completed successfully.
I close it because it is no longer needed.
