### ISSUE TITLE
Remove logback db

### ISSUE THREAD

**Issue by btkawaharahd** [terasolunaorg/terasoluna-gfw#1168]
## Description
> Please write the problem in detail.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

I am using logback db to check the test results, but I can test without using it.

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

Modify not to use logback db when checking the test result.

## Affect versions
> Version in which the problem occurs. **Current version if not known.**
> If there is a feature suggestion, please delete it.

- 5.x.x.RELEASE

## Issue links
> Links to related issues.

- #1166

**Comment by btkatoufm** [comment]
Since DBAppender has been disabled since Logback 1.2.8 and the functionality was moved to logback-classic-db in 1.2.11.1, we decided to review logback-related dependencies.
As a result of the review, we have modified DBAppender not to be used in the terasoluna-gfw Test case, since there is no point in storing logs in DB in the first place.

**Comment by btkatoufm** [comment]
There seems to be a lack of correction.
Let's review it again.
https://github.com/terasolunaorg/terasoluna-gfw/pull/1171#issuecomment-1197499947
