### ISSUE TITLE
Change BeanMapper from Dozer to MapStruct

### ISSUE THREAD

**Issue by btonokit** [terasolunaorg/terasoluna-gfw#1183]
## Description
> Please write the problem in detail.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

It turns out that Dozer doesn't work on Jakarta EE9. Migrate to MapStruct as an alternative BeanMapper.

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

- Remove Dozer dependency from pom.xml and add MapStruct dependency.
- ~~Add necessary settings for MapStruct to `maven-compiler-plugin`.~~

## Affect versions
> Version in which the problem occurs. **Current version if not known.**
> If there is a feature suggestion, please delete it.

- 5.x.x.RELEASE

## Issue links
> Links to related issues.

- #xx

**Comment by btkatoufm** [comment]
The migration destination is also guided by [Dozer](https://github.com/DozerMapper/dozer#project-activity
), which suggests [mapstruct](https://github.com/mapstruct/mapstruct) or [modelmapper](https://github.com/modelmapper/modelmapper).
After consideration, TERASOLUNA has decided to use mapstruct.

**Comment by btonokit** [comment]
Since it is up to the user to use MapStruct and lombok, the MapStruct configuration in maven-compiler-plugin is done in a blank project.
https://github.com/terasolunaorg/terasoluna-gfw/pull/1184#discussion_r970447422

**Comment by btkatoufm** [comment]
To elaborate a bit more, you need to configure to maven-compiler-plugin in order to use mapstruct. (https://mapstruct.org/documentation/installation/#apache-maven)
If you want to use mapstruct and lombok together, you also need to add the configuration for lombok to maven-compiler-plugin. (https://mapstruct.org/documentation/1.5/reference/html/#lombok)

We thought about using terasoluna-gfw to configure the maven-compiler-plugin, but we decided to configure it in the blank project so that users can make their own decisions, since there is a large dependency on users. 

Therefore, the only modifications to terasoluna-gfw are the removal of dozer and the addition of mapstruct.

**Comment by btonokit** [comment]
No Lombok dependencies are set in maven-compiler-plugin, but version management is performed within gfw-parent.
https://github.com/terasolunaorg/terasoluna-gfw/pull/1184#discussion_r972509384
Reopen for adding version properties.
