### ISSUE TITLE
Add constraints of Bean Validation

### ISSUE THREAD

**Issue by making** [terasolunaorg/terasoluna-gfw#372]
## Description
Add new constraints.

## Possible Solutions

Add following annotations

* ~~`@After`~~ (manage on #411)
* ~~`@Before`~~ (manage on #411)
* `@ByteMax`
* `@ByteMin`
* `@Compare`

## Affects Version/s
* N/A

## Fix Version/s
- [x]  5.1.0
- [x] 5.1.0 (remove `joda-time`)

**Comment by making** [comment]
New constraints are introduced by https://github.com/terasolunaorg/terasoluna-gfw/commit/3ebacea1e64a16136bc92abde4a7032e4d69e499 .

Travis.yml should be updated.

**Comment by making** [comment]
Other tasks

- [ ] setting compiler version (1.8)
- [ ] setting travis-ci
- [ ] polish javadoc

**Comment by btshimizukza** [comment]
@making , @btyoshikawaa 

I've check a current API specifications. Please check comments.

# Comments for specification

## For `@After` & `@Before`

### About date time of the comparing destination

- [ ] Currently, supported values is constants value(fix value) specified by value attribute only. However a lot of past project that i experienced, there was using property value managed on properties file instead of constants value. Does consider this already ? or Can you consider this ?

For example, candidates are : 

* Support a getting form system property using `${propertyKey: defaultValue}` syntax (e.g. `@Before("${minStartDate: 2016-01-01}")`).

* Support an overriding of default implementation using  `ComparingDestinationValueResolver` (temporary name) interface.

* etc ...

## For `@Compare`

### About `null` value

- [ ] Currently, if source property value or destination property value is `null`, `CompareValidator` return the `true` as out of validation target. If `LESS_THAN*` or `GRATER_THAN*` operator is used, problem is nothing. However, if  `EQUAL` operator is used, i think it is not intuitive.

| Source value | Destination value | Validation result <br> on current specification | Intuitive? |
| ----- | ----- | ----- | ----- |
| `null` | `null` | `true` | Yes |
| `"test"` | `null` | `true` | **No** |
| `null` | `"test"` | `true` | **No** |
| `"test"` | `"test"` | `true` | Yes |
| `"test"` | `"case"` | `false` | Yes |

Probably, i think that it expect to return `false` in a lot of cases.
What do you think ?

### About binding node of error message

- [ ] Currently, binding node of error message is fixed on source property. I think better that it allow selective from inner enum(`SOURCE`(default), `DESTINATION` or `ROOT_BEAN`).

**Comment by making** [comment]
- [ ] As for `@After`, `@Before`, `inclusive` attibute would be better. (default `false`)

**Comment by kazuki43zoo** [comment]
- [ ] We will consider to use the `CharSequence` instead of `String` in Validator for `@ByteMin` and `ByteMax`.

**Comment by btshimizukza** [comment]
other tasks is uncompleted.

**Comment by btshimizukza** [comment]
- [ ] `@ReportAsSingleViolation` is unnecessary on new constraint annotations.

**Comment by ikeyat** [comment]
Defer ``@Before`` and ``@After`` annotations to #411.

These annotations need more discussion whether there are such requirements for date comparison validation for fixed dates.
In addition, this annotations requires cross JDK ver. compile.
We would like to exclude this from 5.1.0 release.

**Comment by ikeyat** [comment]
@btyoshikawaa 
Add the background of #416 in this issue  to be able to trace why you improved.

**Comment by btyoshikawaa** [comment]
@ikeyat 
> Add the background of #416 in this issue to be able to trace why you improved.

I'd added this in https://github.com/terasolunaorg/terasoluna-gfw/pull/416#issue-117973969.

**Comment by ikeyat** [comment]
@btyoshikawaa 
I wanted you to add it on this issue, not PR... Sorry for my poor English.

**Comment by ikeyat** [comment]
For null values discussed on previous comment...

If either the left and right property value is  null, in som cases Valid is expected, but in some cases it is not. 
I add new attribute `boolean requireBoth` for `@Compare` annotation based on our conversation.

|   left   |   right  |  requireBoth=true | requireBoth=false |
|:--------:|:--------:|:-----------------:|:-----------------:|
| not null | not null | (comparison result) | (comparison result) |
|   null   | not null |     **FALSE**     |      **TRUE**     |
| not null |   null   |     **FALSE**     |      **TRUE**     |
|   null   |   null   |        TRUE       |        TRUE       |

**Comment by ikeyat** [comment]
I merged at #416 and close this.

**Comment by kazuki43zoo** [comment]
Remove `joda-time` on `pom.xml`.
In `terasoluna-gfw-validator`, joda-time does not use.

**Comment by ikeyat** [comment]
@btyoshikawaa 
- [ ] Please Add API doc for new annotations.

**Comment by ikeyat** [comment]
We've completed javadoc coverage.
