### ISSUE TITLE
Support Gradle build tools

### ISSUE THREAD

**Issue by donhuvy** [terasolunaorg/terasoluna-gfw#625]
## Description

Currently, many active enterprise Java project supported Gradle build system (such as Hibernate ORM, Spring Boot, etc.). I hope Terasoluna will support Gradle build system. Maven is sufficient, but quite old. Gradle is cutting-edge, best-practice, and more powerful (Gradle tasks defined by Groovy programming language, not merely a configuration xml file like Maven, support polygot, more easy for continuous integration, also for continuous delivery).
## Possible Solutions

[Gralde 3.x](https://gradle.org/)
Support Gradle and Maven simultaneously.

**Comment by ikeyat** [comment]
Thanks for the request! Your opinion is correct and Gradle is also popular and powerful build tools.
But we have no plan to support Gradle aggressively because of following reasons.
* Gradle is very convenient and flexibility but can cause loose script. Our main targets of this framework are large enterprise projects. Most of them want to protect their script from looseness.
* Double maintenance of maven and groovy is heavy for us and it causes mistakes.
* Gradle lovers can use gradle if they write script by themselves to use the compatibility to maven repositories.

I'm happy if you understand our stance.

**Comment by btkatoufm** [comment]
There are no additional requests, so I will close it.
