### ISSUE TITLE
Add dependency definition of javax.mail

### ISSUE THREAD

**Issue by btkobayashirun** [terasolunaorg/terasoluna-gfw#945]
## Description
Version 5.6.0 decided not to migrate from javax to Jakarta.
In spring-boot-dependencies 2.2.2, dependency definition of javax.mail does not exist, so add dependency definition.

## Possible Solutions
- Add javax.mail dependency definition to terasoluna-gfw-parent.
- Exclude javax.activation:activation from com.sun.mail:javax.mail , and add com.sun.activation:javax.activation 1.2.0(see https://github.com/terasolunaorg/terasoluna-gfw/issues/945#issuecomment-572451890 )

## Affects Version/s
- 5.X.X.RELEASE

#### Add javax.mail
- [x] 5.6.0 (master)
#### Exclude javax.activation:activation and add com.sun.activation:javax.activation 1.2.0
- [x] 5.6.0 (master)

## Issue Links
- #XXX

**Comment by btyanagawamg** [comment]
Spring Boot 2.2.2 supports javax.activation-api 1.2.0 ,
https://docs.spring.io/spring-boot/docs/2.2.2.RELEASE/reference/htmlsingle/#dependency-versions-coordinates

but com.sun.mail:javax.mail depends javax.activation:activation 1.1 .
https://mvnrepository.com/artifact/com.sun.mail/javax.mail/1.6.2

So we decide to use activation 1.2.0 .

At terasoluna-gfw , exclude javax.activation:activation from com.sun.mail:javax.mail , and add com.sun.activation:javax.activation 1.2.0 .
https://mvnrepository.com/artifact/com.sun.activation/javax.activation

Above reason is because javax.activation:activation most recent version is 1.1.1
https://mvnrepository.com/artifact/javax.activation/activation

**Comment by btiwahorisu** [comment]
Since `javax.mail` is not supported in spring-boot, library definition is added to terasoluna-gfw.
However, since it is not necessary to use the old javax.mail, I will guide you to use `jakarta.mail` in the future.
Therefore, delete `javax.mail` and` javax.activation` defined in terasoluna-gfw.
